
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jun 06 18:23:57 CDT 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLECHA = 3;
  public static final int error = 1;
  public static final int PUNTO_COMA = 4;
  public static final int SIMB = 5;
  public static final int OR = 2;
  public static final int EOF = 0;
}

