
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jun 05 20:51:44 CDT 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CERR_POSI = 3;
  public static final int CERR_ESTR = 2;
  public static final int PAR_IZQ = 8;
  public static final int PUNTO_COMA = 7;
  public static final int FLECHA = 6;
  public static final int CONCAT = 10;
  public static final int PAR_DER = 9;
  public static final int EOF = 0;
  public static final int SIMB = 11;
  public static final int INTERR = 4;
  public static final int error = 1;
  public static final int OR = 5;
}

