
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jun 17 19:58:26 CDT 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 15;
  public static final int LT = 20;
  public static final int NE = 17;
  public static final int ELSE = 25;
  public static final int ASGN = 9;
  public static final int PYC = 13;
  public static final int OR = 14;
  public static final int WHILE = 26;
  public static final int NOT = 18;
  public static final int RBRA = 12;
  public static final int POW = 8;
  public static final int SWITCH = 28;
  public static final int IF = 24;
  public static final int LBRA = 11;
  public static final int GT = 22;
  public static final int LE = 19;
  public static final int NUM = 33;
  public static final int SUB = 3;
  public static final int EOF = 0;
  public static final int BREAK = 31;
  public static final int DIV = 5;
  public static final int ADD = 2;
  public static final int GE = 21;
  public static final int CASE = 29;
  public static final int PRINT = 23;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int DEFAULT = 30;
  public static final int RPAR = 7;
  public static final int FOR = 27;
  public static final int MUL = 4;
  public static final int NL = 10;
  public static final int VAR = 34;
  public static final int LPAR = 6;
  public static final int UMINUS = 32;
}

